name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
    schedule:
      - cron: '0 */6 * * *'  # Roda a cada 6 horas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-telegram-bot
          pip install spacy
          pip install nltk

      - name: Install SpaCy models
        run: |
          python -m spacy download pt_core_news_sm
          python -m spacy download pt_core_news_md
          python -m spacy download en_core_web_sm
          python -m spacy download en_core_web_md

      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt')"
          python -c "import nltk; nltk.download('stopwords')"
          python -c "import nltk; nltk.download('averaged_perceptron_tagger')"
          python -c "import nltk; nltk.download('wordnet')"
          python -c "import nltk; nltk.download('omw-1.4')"

      - name: Debug - List files (opcional)
        run: ls -R Codigos_Dicionarios  # Lista os arquivos da pasta para verificar se o biblia.json está lá

      - name: Run Telegram bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Aqui você usa o secret
        run: |
          cd Codigos_Dicionarios
          python biblia_bot.py  
