name: Run Bot

on:
  push:
    branches:
      - main  # O workflow será executado quando você fizer push na branch principal
  schedule:
    - cron: "0 * * * *"  # Executa a cada hora, você pode ajustar conforme sua necessidade

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Substitua pela versão do Python que você usa
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que o caminho do arquivo esteja correto

      - name: Run bot
        run: |
          python Codigos_Dicionarios/biblia_bot.py  # Caminho correto para o seu bot
